apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: test-stage-env-deploy-pipeline
description: gke deployment pipeline
serialPipeline:
  stages:
    - targetId: stage-db
      profiles:
        - stage-db
    - targetId: stage-app
      profiles:
        - stage-app

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: stage-db
description: stage cluster
requireApproval: true
gke:
  cluster: projects/rd-application-group/locations/us-east4/clusters/example-private-cluster
executionConfigs:
- defaultPool:
    serviceAccount: cloudbuild-sa@rd-application-group.iam.gserviceaccount.com
  usages:
  - RENDER
  - DEPLOY

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: stage-app
description: stage cluster
gke:
  cluster: projects/rd-application-group/locations/us-east4/clusters/example-private-cluster
executionConfigs:
- defaultPool:
    serviceAccount: cloudbuild-sa@rd-application-group.iam.gserviceaccount.com
  usages:
  - RENDER
  - DEPLOY